CREATE TABLE account
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    OWNER INT DEFAULT 0 NOT NULL,
    NAME VARCHAR(64) DEFAULT '' NOT NULL,
    TYPE INT DEFAULT 0 NOT NULL,
    SOURCE INT DEFAULT 0 NOT NULL,
    RISK_GRADE INT DEFAULT 0 NOT NULL,
    CARD_TYPE INT DEFAULT 0 NOT NULL,
    CARD_NUM VARCHAR(64) DEFAULT '' NOT NULL,
    PHONE VARCHAR(32) DEFAULT '' NOT NULL,
    MOBILE VARCHAR(32) DEFAULT '' NOT NULL,
    POST_CODE VARCHAR(16) DEFAULT '' NOT NULL,
    FAX VARCHAR(16) DEFAULT '' NOT NULL,
    COMPANY VARCHAR(64) DEFAULT '' NOT NULL,
    OPEN_BANK VARCHAR(64) DEFAULT '' NOT NULL,
    BANK_NAME VARCHAR(64) DEFAULT '' NOT NULL,
    BANK_ACCOUNT VARCHAR(64) DEFAULT '' NOT NULL,
    OWNERSHIP VARCHAR(64) DEFAULT '' NOT NULL,
    INDUSTRY INT DEFAULT 0 NOT NULL,
    PROVINCE INT DEFAULT 0 NOT NULL,
    CITY INT DEFAULT 0 NOT NULL,
    COUNTY INT DEFAULT 0 NOT NULL,
    ADDRESS VARCHAR(255) DEFAULT '' NOT NULL,
    REMARK VARCHAR(512) DEFAULT '' NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE attachment
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DICTIONARY_ID INT DEFAULT 0 NOT NULL,
    MODULE_ID INT DEFAULT 0 NOT NULL,
    TYPE INT DEFAULT 0 NOT NULL,
    ADDRESS VARCHAR(512) DEFAULT '' NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE contact
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ACCOUNT_ID INT,
    SUPPLIER_ID INT,
    OWNER INT,
    NAME VARCHAR(64) DEFAULT '' NOT NULL,
    SOURCE INT NOT NULL,
    DEPARTMENT VARCHAR(32) DEFAULT '' NOT NULL,
    POSITION VARCHAR(32) DEFAULT '' NOT NULL,
    PHONE VARCHAR(32) DEFAULT '' NOT NULL,
    MOBILE VARCHAR(23) DEFAULT '' NOT NULL,
    EMAIL VARCHAR(32) DEFAULT '' NOT NULL,
    FAX VARCHAR(32) DEFAULT '' NOT NULL,
    POST_CODE VARCHAR(32) DEFAULT '' NOT NULL,
    PROVINCE VARCHAR(32) DEFAULT '0' NOT NULL,
    CITY VARCHAR(32) DEFAULT '0' NOT NULL,
    COUNTY VARCHAR(32) DEFAULT '0' NOT NULL,
    ADDRESS VARCHAR(512) DEFAULT '' NOT NULL,
    REMARK VARCHAR(512) DEFAULT '' NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE contract
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ORDER_ID INT DEFAULT 0 NOT NULL,
    ACCOUNT_ID INT DEFAULT 0 NOT NULL,
    NAME VARCHAR(128) DEFAULT '' NOT NULL,
    CODE VARCHAR(32) DEFAULT '' NOT NULL,
    TYPE INT DEFAULT 0 NOT NULL,
    GATHER_CODE VARCHAR(128) DEFAULT '' NOT NULL,
    REDEEM_TYPE INT DEFAULT 0 NOT NULL,
    CONTENT LONGTEXT NOT NULL,
    SIGN_TIME DATETIME NOT NULL,
    EFFECT_TIME DATETIME NOT NULL,
    BEREFT_TIME DATETIME NOT NULL,
    REMARK VARCHAR(512) DEFAULT '' NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE customer
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    OWNER INT DEFAULT 0 NOT NULL,
    NAME VARCHAR(64) DEFAULT '' NOT NULL,
    TYPE INT DEFAULT 0 NOT NULL,
    SOURCE INT DEFAULT 0 NOT NULL,
    RISK_GRADE INT DEFAULT 0 NOT NULL,
    CARD_TYPE INT DEFAULT 0 NOT NULL,
    CARD_NUM VARCHAR(64) DEFAULT '' NOT NULL,
    PHONE VARCHAR(32) DEFAULT '' NOT NULL,
    MOBILE VARCHAR(32) DEFAULT '' NOT NULL,
    POST_CODE VARCHAR(16) DEFAULT '' NOT NULL,
    FAX VARCHAR(16) DEFAULT '' NOT NULL,
    COMPANY VARCHAR(64) DEFAULT '' NOT NULL,
    OPEN_BANK INT DEFAULT 0 NOT NULL,
    BANK_NAME VARCHAR(64) DEFAULT '' NOT NULL,
    BANK_ACCOUNT VARCHAR(64) DEFAULT '' NOT NULL,
    OWNERSHIP VARCHAR(64) DEFAULT '' NOT NULL,
    INDUSTRY INT DEFAULT 0 NOT NULL,
    PROVINCE INT DEFAULT 0 NOT NULL,
    CITY INT DEFAULT 0 NOT NULL,
    COUNTY INT DEFAULT 0 NOT NULL,
    ADDRESS VARCHAR(255) DEFAULT '' NOT NULL,
    REMARK VARCHAR(512) DEFAULT '' NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE lead
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    OWNER INT DEFAULT 0 NOT NULL,
    COMPANY VARCHAR(64) DEFAULT '' NOT NULL,
    NAME VARCHAR(64) DEFAULT '' NOT NULL,
    DEPARTMENT VARCHAR(64) DEFAULT '' NOT NULL,
    POSITION VARCHAR(64) DEFAULT '' NOT NULL,
    EMAIL VARCHAR(64) DEFAULT '' NOT NULL,
    PHONE VARCHAR(32) DEFAULT '' NOT NULL,
    FAX VARCHAR(32) DEFAULT '' NOT NULL,
    MOBILE VARCHAR(32) DEFAULT '' NOT NULL,
    SOURCE INT DEFAULT 0 NOT NULL,
    STATUS INT DEFAULT 0 NOT NULL,
    CARD_TYPE INT DEFAULT 0 NOT NULL,
    CARD_NUM VARCHAR(64) DEFAULT '' NOT NULL,
    INDUSTRY INT DEFAULT 0 NOT NULL,
    POST_CODE VARCHAR(16) DEFAULT '' NOT NULL,
    ADDRESS VARCHAR(256) DEFAULT '' NOT NULL,
    REMARK VARCHAR(512) DEFAULT '' NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE market_activity
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) DEFAULT '' NOT NULL,
    TYPE INT DEFAULT 0 NOT NULL,
    ACTIVITY_STATUS INT DEFAULT 0 NOT NULL,
    BEGIN_DATA DATETIME NOT NULL,
    END_DATA DATETIME NOT NULL,
    PREDICT_COST REAL DEFAULT 0 NOT NULL,
    REALITY_COST REAL DEFAULT 0 NOT NULL,
    TIMES INT DEFAULT 0 NOT NULL,
    EXPECT_EFFECT VARCHAR(256) DEFAULT '' NOT NULL,
    EXPECT_SUCCESS_RATE REAL DEFAULT 0 NOT NULL,
    STATUS INT DEFAULT 0 NOT NULL,
    SPONSOR INT DEFAULT 0 NOT NULL,
    BOSSHEAD INT DEFAULT 0 NOT NULL,
    REMARK VARCHAR(512) DEFAULT '' NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE memoir
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TYPE INT DEFAULT 0 NOT NULL,
    MODULE_ID INT DEFAULT 0 NOT NULL,
    DEPARTMENT_ID INT DEFAULT 0 NOT NULL,
    EMPLOYEE_ID INT DEFAULT 0 NOT NULL,
    SUMMARY VARCHAR(1024) DEFAULT '' NOT NULL,
    REMARK VARCHAR(512) DEFAULT '' NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE memoir_user
(
    ID INT PRIMARY KEY NOT NULL,
    MEMOIR_ID INT DEFAULT 0 NOT NULL,
    USER_ID INT DEFAULT 0 NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE msg_user
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    MSG_ID INT DEFAULT 0,
    USER_ID INT DEFAULT 0,
    STATUS INT DEFAULT 0,
    CREATOR_ID INT DEFAULT 0,
    CREATED_TIME DATETIME,
    MODIFIER_ID INT DEFAULT 0,
    MODIFIED_TIME DATETIME
);
CREATE TABLE notice
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT VARCHAR(255) DEFAULT '' NOT NULL,
    SENT_TIME DATETIME NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE `order`
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PRODUCT_ID INT DEFAULT 0 NOT NULL,
    ACCOUNT_ID INT DEFAULT 0 NOT NULL,
    CODE VARCHAR(32) NOT NULL,
    STATUS INT DEFAULT 0 NOT NULL,
    INVESTMENT_WAY INT DEFAULT 0 NOT NULL,
    PURCHASE_MONEY REAL NOT NULL,
    EARNING_RATE REAL NOT NULL,
    ADVANCE_REDEEM_RATE REAL NOT NULL,
    REDEEM_FORMULA VARCHAR(128) NOT NULL,
    SALES_PERSON_ID INT DEFAULT 0 NOT NULL,
    SALES_MANAGER_ID INT DEFAULT 0 NOT NULL,
    SALES_MAJORDOMO_ID INT DEFAULT 0 NOT NULL,
    ORDER_END_TIME DATETIME NOT NULL,
    REMARK VARCHAR(512) DEFAULT '' NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE product
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PROJECT_ID INT DEFAULT 0 NOT NULL,
    NAME VARCHAR(128) DEFAULT '' NOT NULL,
    CODE VARCHAR(32) DEFAULT '' NOT NULL,
    TYPE INT DEFAULT 0 NOT NULL,
    START_SELL_MONEY REAL DEFAULT 0 NOT NULL,
    MIN_ERNING_RATE REAL DEFAULT 0 NOT NULL,
    MAX_ERNING_RATE REAL DEFAULT 0 NOT NULL,
    EXPECT_PROFIT REAL DEFAULT 0 NOT NULL,
    SALE_LIMIT INT DEFAULT 0 NOT NULL,
    SALE_UNIT INT DEFAULT 0 NOT NULL,
    SALE_BEGIN_TIME DATETIME NOT NULL,
    SALE_END_TIME DATETIME NOT NULL,
    ADVANCE_REDEEM_RATE REAL NOT NULL,
    ADVANCE_REDEEM_FORMULA VARCHAR(216) DEFAULT '' NOT NULL,
    IS_EFFECT CHAR(1) DEFAULT '1' NOT NULL,
    REMARK VARCHAR(512) DEFAULT '' NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE project
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    SUPPLIER_ID INT DEFAULT 0 NOT NULL,
    CODE VARCHAR(64) DEFAULT '' NOT NULL,
    NAME VARCHAR(128) DEFAULT '' NOT NULL,
    FINANCE_LIMIT REAL DEFAULT 0 NOT NULL,
    BEGIN_TIME DATETIME NOT NULL,
    BEFORE_FINANCE_CYCLE INT DEFAULT 0 NOT NULL,
    FINANCE_CYCLE INT DEFAULT 0 NOT NULL,
    OPEN_TIME DATETIME NOT NULL,
    DENDLINE_TIME DATETIME NOT NULL,
    EARNING_RATE REAL DEFAULT 0 NOT NULL,
    ADVANCE_REDEEM_RATE REAL DEFAULT 0 NOT NULL,
    PAY_TYPE INT DEFAULT 0 NOT NULL,
    REMARK VARCHAR(512) DEFAULT '' NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE sales_target
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ORG_ID INT DEFAULT 0 NOT NULL,
    BARGAIN_MONEY REAL NOT NULL,
    UNIT INT DEFAULT 0 NOT NULL,
    REMARK VARCHAR(512) NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE sm_component
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(32) DEFAULT '' NOT NULL,
    NAME VARCHAR(64) DEFAULT '' NOT NULL,
    URL VARCHAR(64) DEFAULT '' NOT NULL,
    REMARK VARCHAR(512) DEFAULT '' NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE sm_dictionary
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `KEY` VARCHAR(64) DEFAULT '' NOT NULL,
    VALUE VARCHAR(64) DEFAULT '' NOT NULL,
    PARENT_ID INT DEFAULT 0,
    REMARK VARCHAR(512) DEFAULT '' NOT NULL,
    CREATOR_ID INT UNSIGNED DEFAULT 0,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FULLNAME VARCHAR(64) DEFAULT '' NOT NULL,
    SIMPLENAME VARCHAR(64) DEFAULT '' NOT NULL
);
CREATE TABLE sm_function
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    MENU_ID INT,
    CODE VARCHAR(32) DEFAULT '0' NOT NULL,
    NAME VARCHAR(64) DEFAULT '' NOT NULL,
    URL VARCHAR(64) DEFAULT '' NOT NULL,
    REMARK VARCHAR(512) DEFAULT '' NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIVILEGE_LEVEL_ID INT DEFAULT 0
);
CREATE TABLE sm_menu
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(32) DEFAULT '',
    NAME VARCHAR(32) DEFAULT '' NOT NULL,
    PARENT_MENU_ID INT,
    URL VARCHAR(64) DEFAULT '',
    IS_ACTIVE CHAR(1) DEFAULT '1' NOT NULL,
    `ORDER` INT DEFAULT 0 NOT NULL,
    SEQ INT DEFAULT 0 NOT NULL,
    LEVEL INT DEFAULT 0 NOT NULL,
    OPEN_TYPE INT DEFAULT 0 NOT NULL,
    REMARK VARCHAR(512) DEFAULT '' NOT NULL,
    CREATOR_ID INT,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SHOW_LOCATION_ID INT,
    TRIGGER_ID INT,
    IS_LEAF TINYINT NOT NULL
);
CREATE TABLE sm_org
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(32) NOT NULL,
    TYPE INT DEFAULT 0 NOT NULL,
    PARENT_ORG_ID INT,
    SHORT_NAME VARCHAR(64) DEFAULT '' NOT NULL,
    FULL_NAME VARCHAR(128) DEFAULT '' NOT NULL,
    ADDRESS VARCHAR(512) DEFAULT '' NOT NULL,
    ZIP_CODE VARCHAR(32) DEFAULT '' NOT NULL,
    PHONE VARCHAR(32) NOT NULL,
    EMAIL VARCHAR(32) DEFAULT '' NOT NULL,
    WEB_SITE VARCHAR(64) DEFAULT '' NOT NULL,
    STATUS INT,
    `ORDER` INT DEFAULT 0 NOT NULL,
    REMARK VARCHAR(512) DEFAULT '' NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME DATETIME NOT NULL,
    IS_LEAF TINYINT NOT NULL,
    LEVEL INT
);
CREATE TABLE sm_org_role
(
    ORG_ID INT DEFAULT 0 NOT NULL,
    ROLE_ID INT DEFAULT 0 NOT NULL,
    PRIMARY KEY ( ORG_ID, ROLE_ID )
);
CREATE TABLE sm_position
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(32) DEFAULT '' NOT NULL,
    NAME VARCHAR(64) DEFAULT '' NOT NULL,
    PARENT_POS_ID INT DEFAULT 0 NOT NULL,
    PARTY_ID INT DEFAULT 0 NOT NULL,
    SORT_NO INT DEFAULT 0 NOT NULL,
    STATUS INT DEFAULT 0 NOT NULL,
    REMARK VARCHAR(215) DEFAULT '' NOT NULL,
    CREATEOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE sm_role
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(255) DEFAULT '' NOT NULL,
    NAME VARCHAR(255) DEFAULT '' NOT NULL,
    TYPE INT DEFAULT 0 NOT NULL,
    REMARK VARCHAR(255) DEFAULT '' NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT,
    MODIFIED_TIME TIMESTAMP
);
CREATE TABLE sm_role_com
(
    ROLE_ID INT DEFAULT 0 NOT NULL,
    COM_ID INT DEFAULT 0 NOT NULL,
    PRIMARY KEY ( ROLE_ID, COM_ID )
);
CREATE TABLE sm_role_func
(
    ROLE_ID INT DEFAULT 0 NOT NULL,
    FUNC_ID INT DEFAULT 0 NOT NULL,
    PRIMARY KEY ( ROLE_ID, FUNC_ID )
);
CREATE TABLE sm_trace_log
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(64) DEFAULT '' NOT NULL,
    TIME DATETIME NOT NULL,
    LEVEL INT DEFAULT 0 NOT NULL,
    MESSAGE LONGTEXT NOT NULL,
    USER_ID INT DEFAULT 0 NOT NULL
);
CREATE TABLE sm_user
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    LOGIN_NAME VARCHAR(32) DEFAULT '' NOT NULL,
    PASSWORD VARCHAR(64) DEFAULT '' NOT NULL,
    CODE VARCHAR(32) DEFAULT '',
    USER_NAME VARCHAR(32) DEFAULT '' NOT NULL,
    `ORDER` INT,
    IS_ACTIVE CHAR(1) DEFAULT '1' NOT NULL,
    JOB_SITUATION INT DEFAULT 1 NOT NULL,
    SEX CHAR(1) DEFAULT '1' NOT NULL,
    PHONE VARCHAR(32) DEFAULT '' NOT NULL,
    MOBILE VARCHAR(32) DEFAULT '' NOT NULL,
    EMAIL VARCHAR(32) DEFAULT '' NOT NULL,
    QQ VARCHAR(16) DEFAULT '' NOT NULL,
    TYPE INT,
    JOB_NAME VARCHAR(64) DEFAULT '' NOT NULL,
    REMARK VARCHAR(512) DEFAULT '' NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT,
    MODIFIED_TIME TIMESTAMP,
    STORE_STATUS INT,
    ORGANIZATION_ID INT NOT NULL
);
CREATE TABLE sm_user_com
(
    USER_ID INT DEFAULT 0 NOT NULL,
    COM_ID INT DEFAULT 0 NOT NULL,
    PRIMARY KEY ( USER_ID, COM_ID )
);
CREATE TABLE sm_user_func
(
    USER_ID INT DEFAULT 0 NOT NULL,
    FUNC_ID INT DEFAULT 0 NOT NULL,
    PRIMARY KEY ( USER_ID, FUNC_ID )
);
CREATE TABLE sm_user_org
(
    USER_ID INT DEFAULT 0 NOT NULL,
    ORG_ID INT DEFAULT 0 NOT NULL,
    PRIMARY KEY ( USER_ID, ORG_ID )
);
CREATE TABLE sm_user_position
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USER_ID INT DEFAULT 0 NOT NULL,
    POS_ID INT DEFAULT 0 NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE sm_user_role
(
    USER_ID INT DEFAULT 0 NOT NULL,
    ROLE_ID INT DEFAULT 0 NOT NULL,
    PRIMARY KEY ( USER_ID, ROLE_ID )
);
CREATE TABLE supplier
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(64) DEFAULT '' NOT NULL,
    TYPE INT DEFAULT 0 NOT NULL,
    PHONE VARCHAR(32) DEFAULT '' NOT NULL,
    MOBILE VARCHAR(32) DEFAULT '' NOT NULL,
    FAX VARCHAR(32) DEFAULT '' NOT NULL,
    PROVINCE VARCHAR(32) DEFAULT '0' NOT NULL,
    CITY VARCHAR(32) DEFAULT '0' NOT NULL,
    COUNTY VARCHAR(32) DEFAULT '0' NOT NULL,
    ADDRESS VARCHAR(512) DEFAULT '' NOT NULL,
    REMARK VARCHAR(512) DEFAULT '' NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE sysmessage
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(64) DEFAULT '' NOT NULL,
    CONTENT LONGTEXT NOT NULL,
    CREATOR_ID INT DEFAULT 0 NOT NULL,
    CREATED_TIME DATETIME NOT NULL,
    MODIFIER_ID INT DEFAULT 0 NOT NULL,
    MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX INDEX_ACCOUNT_OWNER ON account ( OWNER );
CREATE INDEX INDEX_CREATOR_ID ON account ( CREATOR_ID );
CREATE INDEX INDEX_MOBILE ON account ( MOBILE );
CREATE INDEX INDEX_MODIFIED_TIME ON account ( MODIFIED_TIME );
CREATE INDEX INDEX_MODIFIER_ID ON account ( MODIFIER_ID );
CREATE INDEX INDEX_PHONE ON account ( PHONE );
CREATE INDEX INDEX_TYPE ON account ( TYPE );
CREATE INDEX INDEX_CREATE_ID ON attachment ( CREATOR_ID );
CREATE INDEX INDEX_DICTIONARY_ID ON attachment ( DICTIONARY_ID );
CREATE INDEX INDEX_MODIFIED_TIME ON attachment ( MODIFIED_TIME );
CREATE INDEX INDEX_MODIFIER_ID ON attachment ( MODIFIER_ID );
CREATE INDEX INDEX_MODULE_TYPE ON attachment ( MODULE_ID, TYPE );
CREATE INDEX INDEX_TYPE ON attachment ( TYPE );
CREATE INDEX INDEX_CREATOR_ID ON contact ( CREATOR_ID );
CREATE INDEX INDEX_MOBILE ON contact ( MOBILE );
CREATE INDEX INDEX_MODIFIER_ID ON contact ( MODIFIER_ID );
CREATE INDEX INDEX_NAME ON contact ( NAME );
CREATE INDEX INDEX_OWNER ON contact ( OWNER );
CREATE INDEX INDEX_PHONE ON contact ( PHONE );
CREATE INDEX INDEX_SUPPLIER_ID ON contact ( SUPPLIER_ID );
CREATE INDEX INDEX_TYPE ON contact ( ACCOUNT_ID );
CREATE INDEX INDEX_ACCOUNT_ID ON contract ( ACCOUNT_ID );
CREATE INDEX INDEX_CREATOR_ID ON contract ( CREATOR_ID );
CREATE INDEX INDEX_MODIFIED_TIME ON contract ( MODIFIED_TIME );
CREATE INDEX INDEX_MODIFIER_ID ON contract ( MODIFIER_ID );
CREATE INDEX INDEX_ORDER_ID ON contract ( ORDER_ID );
CREATE INDEX INDEX_TYPE ON contract ( TYPE );
CREATE INDEX INDEX_ACCOUNT_OWNER ON customer ( OWNER );
CREATE INDEX INDEX_CREATOR_ID ON customer ( CREATOR_ID );
CREATE INDEX INDEX_MOBILE ON customer ( MOBILE );
CREATE INDEX INDEX_MODIFIED_TIME ON customer ( MODIFIED_TIME );
CREATE INDEX INDEX_MODIFIER_ID ON customer ( MODIFIER_ID );
CREATE INDEX INDEX_PHONE ON customer ( PHONE );
CREATE INDEX INDEX_TYPE ON customer ( TYPE );
CREATE INDEX INDEX_CREATER_ID ON lead ( CREATOR_ID );
CREATE INDEX INDEX_MOBILE ON lead ( MOBILE );
CREATE INDEX INDEX_MODIFIER_ID ON lead ( MODIFIER_ID );
CREATE INDEX INDEX_NAME ON lead ( NAME );
CREATE INDEX INDEX_OWNER ON lead ( OWNER );
CREATE INDEX INDEX_PHONE ON lead ( PHONE );
CREATE INDEX INDEX_STATUS ON lead ( STATUS );
CREATE INDEX `INDEX-CREATOR_ID` ON market_activity ( CREATOR_ID );
CREATE INDEX `INDEX-MODIFIER_ID` ON market_activity ( MODIFIER_ID );
CREATE INDEX INDEX_ACTIVITY_STATUS ON market_activity ( ACTIVITY_STATUS );
CREATE INDEX INDEX_MODIFIED_TIME ON market_activity ( MODIFIED_TIME );
CREATE INDEX INDEX_CREATOR_ID ON memoir ( CREATOR_ID );
CREATE INDEX INDEX_EMPLOYEE_ID ON memoir ( EMPLOYEE_ID );
CREATE INDEX INDEX_ID ON memoir ( ID );
CREATE INDEX INDEX_MODIFIED_TIME ON memoir ( MODIFIED_TIME );
CREATE INDEX INDEX_MODIFIER_ID ON memoir ( MODIFIER_ID );
CREATE INDEX INDEX_MODULE_ID ON memoir ( MODULE_ID );
CREATE INDEX INDEX_TYPE ON memoir ( TYPE );
CREATE INDEX INDEX_CREATOR_ID ON memoir_user ( CREATOR_ID );
CREATE INDEX INDEX_MEMOIR_ID ON memoir_user ( MEMOIR_ID );
CREATE INDEX INDEX_MODIFIED_TIME ON memoir_user ( MODIFIED_TIME );
CREATE INDEX INDEX_MODIFIER_ID ON memoir_user ( MODIFIER_ID );
CREATE INDEX INDEX_USER_ID ON memoir_user ( USER_ID );
CREATE INDEX INDEX_CREATOR_ID ON msg_user ( CREATOR_ID );
CREATE INDEX INDEX_MODIFIED_TIME ON msg_user ( MODIFIED_TIME );
CREATE INDEX INDEX_MODIFIER_ID ON msg_user ( MODIFIER_ID );
CREATE INDEX INDEX_MSG_ID ON msg_user ( MSG_ID );
CREATE INDEX INDEX_USER_ID ON msg_user ( USER_ID );
CREATE INDEX INDEX_CREATOR_ID ON notice ( CREATOR_ID );
CREATE INDEX INDEX_MODIFIED_TIME ON notice ( MODIFIED_TIME );
CREATE INDEX INDEX_MODIFIER_ID ON notice ( MODIFIER_ID );
CREATE UNIQUE INDEX INDEX_CODE ON `order` ( CODE );
CREATE INDEX INDEX_ACCOUNT_ID ON `order` ( ACCOUNT_ID );
CREATE INDEX INDEX_CREATOR_ID ON `order` ( CREATOR_ID );
CREATE INDEX INDEX_MODIFIED_TIME ON `order` ( MODIFIED_TIME );
CREATE INDEX INDEX_MODIFIER_ID ON `order` ( MODIFIER_ID );
CREATE INDEX INDEX_PRODUCT_ID ON `order` ( PRODUCT_ID );
CREATE INDEX INDEX_SALES_MAJORDOMO_ID ON `order` ( SALES_MAJORDOMO_ID );
CREATE INDEX INDEX_SALES_MANAGER_ID ON `order` ( SALES_MANAGER_ID );
CREATE INDEX INDEX_SALES_PERSON_ID ON `order` ( SALES_PERSON_ID );
CREATE UNIQUE INDEX INDEX_CODE ON product ( CODE );
CREATE INDEX INDEX_CREATOR_ID ON product ( CREATOR_ID );
CREATE INDEX INDEX_MODIFIED_TIME ON product ( MODIFIED_TIME );
CREATE INDEX INDEX_MODIFIER_ID ON product ( MODIFIER_ID );
CREATE INDEX INDEX_NAME ON product ( NAME );
CREATE INDEX INDEX_PROJECT_ID ON product ( PROJECT_ID );
CREATE UNIQUE INDEX INDEX_CODE ON project ( CODE );
CREATE INDEX INDEX_CREATOR_ID ON project ( CREATOR_ID );
CREATE INDEX INDEX_MODIFIED_TIME ON project ( MODIFIED_TIME );
CREATE INDEX INDEX_MODIFIER_ID ON project ( MODIFIER_ID );
CREATE INDEX INDEX_NAME ON project ( NAME );
CREATE INDEX INDEX_SUPPLIER_ID ON project ( SUPPLIER_ID );
CREATE INDEX INDEX_CREATOR_ID ON sales_target ( CREATOR_ID );
CREATE INDEX INDEX_MODIFIED_TIME ON sales_target ( MODIFIED_TIME );
CREATE INDEX INDEX_MODIFIER_ID ON sales_target ( MODIFIER_ID );
CREATE INDEX INDEX_ORG_ID ON sales_target ( ORG_ID );
CREATE UNIQUE INDEX INDEX_CODE ON sm_component ( CODE );
CREATE INDEX INDEX_CREATOR_ID ON sm_component ( CREATOR_ID );
CREATE INDEX INDEX_MODIFIED_TIME ON sm_component ( MODIFIED_TIME );
CREATE INDEX INDEX_MODIFIER_ID ON sm_component ( MODIFIER_ID );
CREATE INDEX INDEX_NAME ON sm_component ( NAME );
CREATE INDEX INDEX_URL ON sm_component ( URL );
CREATE INDEX INDEX_CREATOR_ID ON sm_dictionary ( CREATOR_ID );
CREATE INDEX INDEX_KEY_VALUE ON sm_dictionary ( `KEY`, VALUE );
CREATE INDEX INDEX_MODIFIED_TIME ON sm_dictionary ( MODIFIED_TIME );
CREATE INDEX INDEX_MODIFIER_ID ON sm_dictionary ( MODIFIER_ID );
CREATE INDEX INDEX_PARENT_ID ON sm_dictionary ( PARENT_ID );
CREATE INDEX INDEX_CODE ON sm_function ( CODE );
CREATE INDEX INDEX_CREATOR_ID ON sm_function ( CREATOR_ID );
CREATE INDEX INDEX_MENU_ID ON sm_function ( MENU_ID );
CREATE INDEX INDEX_MODIFIED_TIME ON sm_function ( MODIFIED_TIME );
CREATE INDEX INDEX_MODIFIER_ID ON sm_function ( MODIFIER_ID );
CREATE INDEX INDEX_NAME ON sm_function ( NAME );
CREATE INDEX INDEX_CREAOR_ID ON sm_menu ( CREATOR_ID );
CREATE INDEX INDEX_MODIFIER_ID ON sm_menu ( MODIFIER_ID );
CREATE INDEX INDEX_NAME ON sm_menu ( NAME );
CREATE INDEX INDEX_NO ON sm_menu ( CODE );
CREATE INDEX INDEX_CREATOR_ID ON sm_org ( CREATOR_ID );
CREATE INDEX INDEX_MODIFIER_ID ON sm_org ( MODIFIER_ID );
CREATE INDEX INDEX_NO ON sm_org ( CODE );
CREATE INDEX INDEX_SHORT_NAME ON sm_org ( SHORT_NAME );
CREATE INDEX INDEX_ORG_ID ON sm_org_role ( ORG_ID );
CREATE INDEX INDEX_ROLE_ID ON sm_org_role ( ROLE_ID );
CREATE INDEX INDEX_CREATEOR_ID ON sm_position ( CREATEOR_ID );
CREATE INDEX INDEX_MODIFIER_ID ON sm_position ( MODIFIER_ID );
CREATE INDEX INDEX_NAME ON sm_position ( NAME );
CREATE INDEX INDEX_NO ON sm_position ( CODE );
CREATE UNIQUE INDEX INDEX_NAME ON sm_role ( NAME );
CREATE INDEX INDEX_CREATOR_ID ON sm_role ( CREATOR_ID );
CREATE INDEX INDEX_MODIFIER_ID ON sm_role ( MODIFIER_ID );
CREATE INDEX INDEX_NO ON sm_role ( CODE );
CREATE INDEX INDEX_FUNC_ID ON sm_role_func ( FUNC_ID );
CREATE INDEX INDEX_ROLE_ID ON sm_role_func ( ROLE_ID );
CREATE INDEX INDEX_NAME ON sm_trace_log ( NAME );
CREATE INDEX INDEX_USER_ID ON sm_trace_log ( USER_ID );
CREATE UNIQUE INDEX INDEX_LOGIN_NAME ON sm_user ( LOGIN_NAME );
CREATE INDEX INDEX_CREATOR_ID ON sm_user ( CREATOR_ID );
CREATE INDEX INDEX_MODIFIER_ID ON sm_user ( MODIFIER_ID );
CREATE INDEX INDEX_NO ON sm_user ( CODE );
CREATE INDEX INDEX_COM_ID ON sm_user_com ( COM_ID );
CREATE INDEX INDEX_USER_ID ON sm_user_com ( USER_ID );
CREATE INDEX INDEX_FUNC_ID ON sm_user_func ( FUNC_ID );
CREATE INDEX INDEX_USER_ID ON sm_user_func ( USER_ID );
CREATE INDEX INDEX_ORG_ID ON sm_user_org ( ORG_ID );
CREATE INDEX INDEX_USER_ID ON sm_user_org ( USER_ID );
CREATE INDEX `INDEX-USER_ID` ON sm_user_position ( USER_ID );
CREATE INDEX INDEX_CREATOR_ID ON sm_user_position ( CREATOR_ID );
CREATE INDEX INDEX_MODIFIED_TIME ON sm_user_position ( MODIFIED_TIME );
CREATE INDEX INDEX_MODIFIER_ID ON sm_user_position ( MODIFIER_ID );
CREATE INDEX INDEX_POS_ID ON sm_user_position ( POS_ID );
CREATE INDEX INDEX_ROLE_ID ON sm_user_role ( ROLE_ID );
CREATE INDEX INDEX_USER_ID ON sm_user_role ( USER_ID );
CREATE INDEX INDEX_CREATOR_ID ON supplier ( CREATOR_ID );
CREATE INDEX INDEX_MODIFIED_TIME ON supplier ( MODIFIED_TIME );
CREATE INDEX INDEX_MODIFIER_ID ON supplier ( MODIFIER_ID );
CREATE INDEX INDEX_NAME ON supplier ( NAME );
CREATE INDEX INDEX_TYPE ON supplier ( TYPE );
CREATE INDEX INDEX_CREATOR_ID ON sysmessage ( CREATOR_ID );
CREATE INDEX INDEX_MODIFIED_TIME ON sysmessage ( MODIFIED_TIME );
CREATE INDEX INDEX_MODIFIER_ID ON sysmessage ( MODIFIER_ID );
