/*
MySQL Data Transfer
Source Host: 192.168.111.141
Source Database: hxtd
Target Host: 192.168.111.141
Target Database: hxtd
Date: 2014/7/24 13:44:48
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for order
-- ----------------------------
CREATE TABLE `order` (
  `ID` int(4) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `PRODUCT_ID` int(4) NOT NULL DEFAULT '0' COMMENT '产品ID',
  `CUSTOMER_ID` int(4) NOT NULL DEFAULT '0' COMMENT '客户ID',
  `CODE` varchar(32) NOT NULL COMMENT '订单编号',
  `STATUS` int(11) DEFAULT NULL,
  `INVESTMENT_WAY` int(4) NOT NULL DEFAULT '0' COMMENT '投资方式',
  `PURCHASE_MONEY` decimal(10,4) NOT NULL COMMENT '购买金额',
  `EARNING_RATE` float(10,0) NOT NULL COMMENT '收益率',
  `ADVANCE_REDEEM_RATE` float(10,0) NOT NULL COMMENT '提前赎回率',
  `REDEEM_FORMULA` varchar(128) NOT NULL COMMENT '赎回公式',
  `OWNER` int(4) NOT NULL DEFAULT '0' COMMENT '销售人员',
  `SALES_MANAGER_ID` int(4) NOT NULL DEFAULT '0' COMMENT '销售经理',
  `SALES_MAJORDOMO_ID` int(4) NOT NULL DEFAULT '0' COMMENT '销售总监',
  `ORDER_END_TIME` datetime NOT NULL COMMENT '订单结束时间',
  `REMARK` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  `IS_DELETED` int(4) DEFAULT '0' COMMENT '删除标识',
  `CREATOR_ID` int(4) NOT NULL DEFAULT '0' COMMENT '创建者ID',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `MODIFIER_ID` int(4) NOT NULL DEFAULT '0' COMMENT '修改者ID',
  `MODIFIED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `PAY_MONEY` decimal(10,0) DEFAULT '0' COMMENT '支付金额',
  `PAY_STATUS` int(4) DEFAULT '0' COMMENT '付款状态',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `INDEX_CODE` (`CODE`) USING BTREE,
  KEY `INDEX_PRODUCT_ID` (`PRODUCT_ID`) USING BTREE,
  KEY `INDEX_ACCOUNT_ID` (`CUSTOMER_ID`) USING BTREE,
  KEY `INDEX_SALES_PERSON_ID` (`OWNER`) USING BTREE,
  KEY `INDEX_SALES_MANAGER_ID` (`SALES_MANAGER_ID`) USING BTREE,
  KEY `INDEX_SALES_MAJORDOMO_ID` (`SALES_MAJORDOMO_ID`) USING BTREE,
  KEY `INDEX_CREATOR_ID` (`CREATOR_ID`) USING BTREE,
  KEY `INDEX_MODIFIER_ID` (`MODIFIER_ID`) USING BTREE,
  KEY `INDEX_MODIFIED_TIME` (`MODIFIED_TIME`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COMMENT='订单表';

-- ----------------------------
-- Records 
-- ----------------------------
INSERT INTO `order` VALUES ('4', '2', '11', '45648799', '1', '6010101', '12.3000', '12', '12', '12+2', '1', '1', '1', '2014-07-23 00:00:00', '', '0', '1', '2014-07-23 20:23:52', '1', '2014-07-23 20:23:52', '0', '0');
INSERT INTO `order` VALUES ('5', '2', '11', '45648799123123', null, '6010101', '12.3000', '12', '12', '12+2', '1', '1', '1', '2014-07-23 00:00:00', '', '0', '1', '2014-07-24 13:17:49', '1', '2014-07-24 13:17:49', '0', '0');
